import { apiRequest, apiUpload } from "@/lib/api/client";
import type { AccountValidation, Niche, ProjectAutomation, ProjectDashboardData, ProjectInput, QueuedClip, Story } from "./types";
export const getNiches = () => apiRequest<{defaults:Record<string,unknown>;niches:Niche[]}>("/projects/niches");
export const seedNiches = () => apiRequest<{seeded:number;total:number}>("/projects/niches/seed",{method:"POST"});
export const validateAccount = (id:string) => apiRequest<AccountValidation>(`/projects/accounts/${id}/validate`);
export const createAutomationProject = (input:ProjectInput) => apiRequest<ProjectAutomation>("/projects", {method:"POST",json:input});
export const updateAutomationProject = (id:string,input:Partial<ProjectInput>) => apiRequest<ProjectAutomation>(`/projects/${id}`, {method:"PATCH",json:input});
export const getAutomationProject = (id:string) => apiRequest<ProjectAutomation>(`/projects/${id}`);
export const getProjectDashboard = (id:string) => apiRequest<ProjectDashboardData>(`/projects/${id}/dashboard`);
export const getProjectStories = (id:string) => apiRequest<Story[]>(`/projects/${id}/stories`);
export const generateNow = (id:string) => apiRequest<{jobId:string;status:string}>(`/projects/${id}/generate-now`,{method:"POST"});
export const pauseAutomation = (id:string) => apiRequest<ProjectAutomation>(`/projects/${id}/pause`,{method:"POST"});
export const resumeAutomation = (id:string) => apiRequest<ProjectAutomation>(`/projects/${id}/resume`,{method:"POST"});
export const approveStory = (projectId:string,storyId:string) => apiRequest<Story>(`/projects/${projectId}/stories/${storyId}/approve`,{method:"POST"});
export const uploadStoryNow = (projectId:string,storyId:string) => apiRequest<Story>(`/projects/${projectId}/stories/${storyId}/upload-now`,{method:"POST"});
export const rejectStory = (projectId:string,storyId:string) => apiRequest<Story>(`/projects/${projectId}/stories/${storyId}/reject`,{method:"POST"});
export const retryGeneration = (projectId:string,storyId:string) => apiRequest<unknown>(`/projects/${projectId}/stories/${storyId}/retry-generation`,{method:"POST"});
export const retryUpload = (projectId:string,storyId:string) => apiRequest<unknown>(`/projects/${projectId}/stories/${storyId}/retry-upload`,{method:"POST"});
export const deleteAutomationProject = (id:string) => apiRequest<{deleted:boolean}>(`/projects/${id}`,{method:"DELETE"});
export const getApprovedSubreddits = () => apiRequest<string[]>("/projects/reddit/subreddits");
export const validateSubreddit = (subreddit:string) => apiRequest<{valid:boolean;subreddit:string}>("/projects/reddit/validate",{method:"POST",json:{subreddit}});
export const uploadQueuedClip = (projectId:string,formData:FormData) => apiUpload<QueuedClip>("/projects/"+projectId+"/clips",formData);
export const getClipQueue = (projectId:string) => apiRequest<QueuedClip[]>("/projects/"+projectId+"/clips");
export const uploadQueuedClipNow = (projectId:string,clipId:string) => apiRequest<QueuedClip>("/projects/"+projectId+"/clips/"+clipId+"/upload-now",{method:"POST"});
export const retryQueuedClip = (projectId:string,clipId:string) => apiRequest<QueuedClip>("/projects/"+projectId+"/clips/"+clipId+"/retry",{method:"POST"});
export const removeQueuedClip = (projectId:string,clipId:string) => apiRequest<{deleted:boolean}>("/projects/"+projectId+"/clips/"+clipId,{method:"DELETE"});
export const reorderQueuedClips = (projectId:string,clipIds:string[]) => apiRequest<QueuedClip[]>("/projects/"+projectId+"/clips/reorder",{method:"POST",json:{clipIds}});
export const replaceQueuedClip = (projectId:string,clipId:string,file:File) => {const form=new FormData();form.append("video",file);return apiUpload<QueuedClip>("/projects/"+projectId+"/clips/"+clipId+"/file",form,"PUT")};
export const scheduleQueuedClip = (projectId:string,clipId:string,scheduledAt:string) => apiRequest<QueuedClip>("/projects/"+projectId+"/clips/"+clipId+"/schedule",{method:"POST",json:{scheduledAt}});
